
  <a class="nav" href="default.aspx">Home</a>
  <a class="nav" href="Google/default.aspx">Google Report</a>  
  <a class="nav" href="http://mattdecuir.wordpress.com/">Blog</a>
  <a class="nav" href="profile.aspx">About Me</a>
  <a class="nav" href="http://www.linkedin.com/in/mattdecuir">LinkedIn</a>
  <a class="nav" href="http://twitter.com/decuirm">Twitter</a>
  <a class="nav" id="navb" href="http://hypem.com/#!/decuirm">Hypem</a>

